import re
from pathlib import Path

import markdown
from weasyprint import HTML

STYLES_DIR = Path(__file__).parent / "styles"


def _sanitize_filename(topic: str) -> str:
    """Convert topic string to a safe filename slug."""
    clean = re.sub(r"[^\w\s-]", "", topic.lower())
    clean = re.sub(r"[\s]+", "-", clean.strip())
    return clean[:80]


def render_pdf(
    markdown_content: str,
    topic: str,
    output_dir: Path,
) -> Path:
    """Convert a Markdown research report to a professional PDF.

    Returns the path to the generated PDF file.
    """
    # Markdown -> HTML
    extensions = [
        "tables",
        "toc",
        "fenced_code",
        "footnotes",
        "attr_list",
        "md_in_html",
    ]
    md = markdown.Markdown(extensions=extensions)
    html_body = md.convert(markdown_content)

    # Load CSS
    css_path = STYLES_DIR / "report.css"
    css_content = css_path.read_text(encoding="utf-8")

    # Build full HTML document
    full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <style>{css_content}</style>
</head>
<body>
    <div class="report-content">
        {html_body}
    </div>
</body>
</html>
"""

    # Generate PDF — filename: {topic_name}-research.pdf
    filename = f"{_sanitize_filename(topic)}-research.pdf"
    pdf_path = output_dir / filename

    html_doc = HTML(string=full_html)
    html_doc.write_pdf(str(pdf_path))

    return pdf_path


def count_pdf_pages(pdf_path: Path) -> int:
    """Count pages in a PDF generated by weasyprint."""
    html_doc = HTML(filename=str(pdf_path))
    document = html_doc.render()
    return len(document.pages)
